My 'for' loop works.
I understand why it works. What I do not understand is when I run the
JUnit test I get the following failure.

ComparisonFailure: expected:<[]cba> but was:<[null]cba>

I'm assuming [] is null, but why is the test seeing [null] or more
likely, why is my code producing [null]?